name: djtantrum
favicon: null
layout_spectrum: 0.6918229572474957
typography_spectrum: 0.8568715041037649
title: 'DJ TANTRUM '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#a0a0a0'
    - '#b10000'
    - '#008300'
  brandStrength: 0.1875
  lightness: 0.9375
  saturation: 0.10700277611613274
  rhythmicContrast: 0.25
purpose: []
